### ISSUE TITLE
Error when hitting block with sword in creative

### ISSUE THREAD

**Issue by ulxsth** [frengor/UltimateAdvancementAPI#42]
As the title says. Here is the error text:

```
[19:04:16 ERROR]: [STDERR] Event BlockBreakEvent in BreakBlockAdv has thrown an error:
[19:04:16 WARN]: com.fren_gor.ultimateAdvancementAPI.exceptions.UserNotLoadedException: Userbc4290fb-e475-4037-b871-db4f805b0a25 is not currently loaded. May it be offline?
[19:04:16 WARN]: 	at UltimateAdvancementAPI-2.2.3-(1.15-1.19.4).jar//com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils.checkTeamProgressionNotNull(AdvancementUtils.java:224)
[19:04:16 WARN]: 	at UltimateAdvancementAPI-2.2.3-(1.15-1.19.4).jar//com.fren_gor.ultimateAdvancementAPI.database.DatabaseManager.getTeamProgression(DatabaseManager.java:732)
[19:04:16 WARN]: 	at UltimateAdvancementAPI-2.2.3-(1.15-1.19.4).jar//com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils.progressionFromUUID(AdvancementUtils.java:281)
[19:04:16 WARN]: 	at UltimateAdvancementAPI-2.2.3-(1.15-1.19.4).jar//com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils.progressionFromUUID(AdvancementUtils.java:270)
[19:04:16 WARN]: 	at UltimateAdvancementAPI-2.2.3-(1.15-1.19.4).jar//com.fren_gor.ultimateAdvancementAPI.advancement.Advancement.isVisible(Advancement.java:527)
[19:04:16 WARN]: 	at UltimateAdvancementAPI-2.2.3-(1.15-1.19.4).jar//com.fren_gor.ultimateAdvancementAPI.advancement.Advancement.isVisible(Advancement.java:513)
[19:04:16 WARN]: 	at AchievementTest-1.0-SNAPSHOT-all.jar//com.ulxsth.achievementtest.achievements.BreakBlockAdv.lambda$new$0(BreakBlockAdv.java:18)
[19:04:16 WARN]: 	at UltimateAdvancementAPI-2.2.3-(1.15-1.19.4).jar//com.fren_gor.ultimateAdvancementAPI.events.EventManager$EventListener.call(EventManager.java:336)
[19:04:16 WARN]: 	at UltimateAdvancementAPI-2.2.3-(1.15-1.19.4).jar//com.fren_gor.ultimateAdvancementAPI.events.EventManager$EventListener.lambda$new$0(EventManager.java:281)
[19:04:16 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:04:16 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:04:16 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
[19:04:16 WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:369)
[19:04:16 WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:328)
[19:04:16 WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:214)
[19:04:16 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1871)
[19:04:16 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[19:04:16 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[19:04:16 WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[19:04:16 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:04:16 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:04:16 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:04:16 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[19:04:16 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[19:04:16 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:04:16 WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[19:04:16 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[19:04:16 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:04:16 WARN]: 	at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[19:04:16 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[19:04:16 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[19:04:16 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

BreakBlockAdv is a simple tutorial achievement I created, here is the code:

```java
package com.ulxsth.achievementtest.achievements;

import com.fren_gor.ultimateAdvancementAPI.advancement.Advancement;
import com.fren_gor.ultimateAdvancementAPI.advancement.BaseAdvancement;
import com.fren_gor.ultimateAdvancementAPI.advancement.display.AdvancementDisplay;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

public class BreakBlockAdv extends BaseAdvancement {
    public BreakBlockAdv(String key, AdvancementDisplay display, Advancement parent, int maxProgression) {
        super(key, display, parent, maxProgression);

        registerEvent(BlockBreakEvent.class, event -> {
            Player player = event.getPlayer();
            if (isVisible(player)) {
                incrementProgression(player);
            }
        });
    }

    @Override
    public void giveReward(Player player) {
        ItemStack item = new ItemStack(Material.DIAMOND);
        ItemMeta im = item.getItemMeta();
        im.setDisplayName("とてもかたいだいやもんど");
        item.setItemMeta(im);
        player.getInventory().addItem(item);
    }
}
```

This is my first time writing an Issue, so please let me know if there are any flaws

(using DeepL)

**Comment by EscanorTargaryen** [comment]
Hi! I tested the code and it seems to work, in our opinion the error should be looked for in other classes, could you send us the main class of the plugin?

**Comment by ulxsth** [comment]
I just tested it under the same conditions and didn't get the same error. So this may not be an error with this plugin :(

In the meantime, here is the repository for the plugin that implements BreakBlockAdv:
https://github.com/ulxsth/AchievementTest

**Comment by frengor** [comment]
Did you reload before getting the error?

**Comment by ulxsth** [comment]
The reason why the errors start occurring is not well understood, but the behavior after various restarts is as follows:

* /reload confirm after the error occurs: the error continues to occur
* Shutting down the server and starting it again after the error occurs: error subsides.

**Comment by ulxsth** [comment]
I said "with sword" but in fact it was no different with other things in my hand.

**Comment by EscanorTargaryen** [comment]
We know very well that doing /reloads makes our API go wrong, but like any plugin that uses packets! So we recommend that you restart the server every time. However we are leaving your issue open because we will make changes to fix some things about it.

**Comment by ulxsth** [comment]
I understand! Thanks for your thoughtful response <3
