### ISSUE TITLE
Another strange error in console

### ISSUE THREAD

**Issue by envizar** [frengor/UltimateAdvancementAPI#53]
```
[13:57:43 WARN]: [UltimateAdvancementAPI] Task #242845 for UltimateAdvancementAPI v2.2.6 generated an exception
java.lang.IllegalArgumentException: Invalid TeamProgression.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils.validateTeamProgression(AdvancementUtils.java:212) ~[UltimateAdvancementAPI-2.2.6-(1.15-1.20.2)(1).jar:?]
        at com.fren_gor.ultimateAdvancementAPI.events.PlayerLoadingCompletedEvent.<init>(PlayerLoadingCompletedEvent.java:29) ~[UltimateAdvancementAPI-2.2.6-(1.15-1.20.2)(1).jar:?]
        at com.fren_gor.ultimateAdvancementAPI.database.DatabaseManager.lambda$loadPlayerMainFunction$8(DatabaseManager.java:230) ~[UltimateAdvancementAPI-2.2.6-(1.15-1.20.2)(1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2074]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2074]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1495) ~[purpur-1.20.2.jar:git-Purpur-2074]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.20.2.jar:git-Purpur-2074]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[purpur-1.20.2.jar:git-Purpur-2074]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[purpur-1.20.2.jar:git-Purpur-2074]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[purpur-1.20.2.jar:git-Purpur-2074]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```
Purpur 1.20.2

**Comment by frengor** [comment]
Hi! When does this happens? Are there any other errors in the console?

**Comment by envizar** [comment]
> Hi! When does this happens? Are there any other errors in the console?

No other errors, it happens randomly

**Comment by frengor** [comment]
Does it happen after a player enters the server? Is the player leaving just after joining?

**Comment by envizar** [comment]
I can't reproduce it again somewhy

**Comment by frengor** [comment]
I think this might be a duplicate if https://github.com/frengor/UltimateAdvancementAPI/issues/35 then
