### ISSUE TITLE
Geyser Support (works but error upon joining in console)

### ISSUE THREAD

**Issue by Karltroid** [frengor/UltimateAdvancementAPI#79]
This plugin is great! Been using it on the Modern Beta SMP for a while not, even somewhat works on bedrock edition via geyser. However the console gets spammed errors upon a bedrock user joining because this plugin is trying to send a ClinetboundSelectAdvancementsTabPacket that has a null categoryAdvancement.

The following error comes from geyser, but is caused by the packets created from this plugin.

```
[15:28:21 WARN]: [Geyser-Spigot] Could not translate packet ClientboundSelectAdvancementsTabPacket
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.level.GeyserAdvancement.getDisplayData()" because "categoryAdvancement" is null
        at org.geysermc.geyser.session.cache.AdvancementsCache.buildAndShowListForm(AdvancementsCache.java:114) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.JavaSelectAdvancementsTabTranslator.translate(JavaSelectAdvancementsTabTranslator.java:44) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.JavaSelectAdvancementsTabTranslator.translate(JavaSelectAdvancementsTabTranslator.java:37) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:90) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:70) ~[Geyser-Spigot.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[?:4.1.97.Final]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[?:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Karltroid** [comment]
Either the packet's data needs to be fixed or I would be okay with just detecting it being a geyser player via the "." to the left of their name and just not sending this packet.

**Comment by CrazyDev05** [comment]
to me this sounds more like a geyser issue as the plugin should send the correct packets
geyser is just messing up the translation

**Comment by frengor** [comment]
It's a Geyser issue, in the packet's code that field is marked as `@Nullable`.
